In [2]:
# https://towardsdatascience.com/logistic-regression-with-pytorch-3c8bbea594be
import os
os.chdir("/Users/tien/Documents/PythonEnvs/pytorch/")

In [18]:
from sklearn.datasets import make_classification
import numpy as np

In [28]:
from sklearn.model_selection import train_test_split

In [31]:
separable = False
while not separable:
    samples = make_classification(n_samples=1000, n_features=3, n_redundant=0, n_informative=1, n_clusters_per_class=1, flip_y=-1)
    red = samples[0][samples[1] == 0]
    blue = samples[0][samples[1] == 1]
    separable = any([red[:, k].max() < blue[:, k].min() or red[:, k].min() > blue[:, k].max() for k in range(2)])


In [46]:
type(samples)

tuple

In [47]:
type(red)

numpy.ndarray

In [48]:
red

array([[-0.91843468,  0.70915598,  0.59855738],
       [-0.65215249, -0.63457328, -1.43954453],
       [-0.72377186, -0.49505811,  0.89285122],
       ...,
       [-1.11221222,  0.36486744,  0.20402356],
       [-0.72218124,  0.7157978 ,  0.25371903],
       [-0.89523729, -1.61988721, -0.46029027]])

In [20]:
samples = make_classification(n_samples=1000, n_features=3, n_redundant=0, n_informative=1, n_clusters_per_class=1, flip_y=-1)
len(samples)

2

In [32]:
red_labels = np.zeros(len(red))
blue_labels = np.ones(len(blue))

labels = np.append(red_labels,blue_labels)
inputs = np.concatenate((red,blue),axis=0)

In [54]:
inputs = np.concatenate((red,blue),axis=0)

In [55]:
type(labels)

numpy.ndarray

In [59]:
type(labels)

numpy.ndarray

In [56]:
type(inputs)

numpy.ndarray

In [52]:
len(inaputs)

500

In [53]:
inputs

array([[-0.91843468,  0.70915598,  0.59855738,  0.9853249 ,  0.17353672,
        -0.16404289],
       [-0.65215249, -0.63457328, -1.43954453,  0.94405945,  0.16830066,
         0.0325907 ],
       [-0.72377186, -0.49505811,  0.89285122,  0.9844003 ,  0.77607102,
         0.07230648],
       ...,
       [-1.11221222,  0.36486744,  0.20402356,  1.0070798 ,  0.32137222,
         0.36310512],
       [-0.72218124,  0.7157978 ,  0.25371903,  1.20487121,  0.42690081,
         1.92290539],
       [-0.89523729, -1.61988721, -0.46029027,  1.02345773, -0.48022998,
         0.44729715]])

In [33]:
blue_labels

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [34]:
X_train, X_test, y_train,  y_test = train_test_split(
    inputs, labels, test_size=0.33, random_state=42)

In [30]:
X_train

array([[-0.19708682,  0.97095805],
       [-0.71736988, -0.90120261],
       [ 1.12647508,  0.9975317 ],
       ...,
       [-0.31083561,  1.02054944],
       [-1.42289134, -1.53377657],
       [-0.45676698, -1.06460517]])

In [27]:
len(blue_labels)

500

In [23]:
from torch import nn
import torch

In [3]:
from jup.examples.recsys_models.simple_regression import Regression

In [35]:
input_dim = 2
output_dim = 1

In [37]:
lr_model = Regression(input_dim=input_dim, output_dim=output_dim, task='binary', use_bias=True)

In [7]:
criterion = nn.BCELoss()

In [10]:
optimizer = torch.optim.SGD(lr_model.parameters(), lr=0.01)

In [8]:
lr_model.parameters()

<generator object Module.parameters at 0x1294aecf0>

In [40]:
x_train = torch.Tensor(X_train)
x_test = torch.Tensor(X_test)

In [42]:
type(x_train)

torch.Tensor

In [43]:
outputs = lr_model(x_train)

In [44]:
type(outputs)

torch.Tensor

In [41]:
y_train, y_test = torch.Tensor(y_train), torch.Tensor(y_test)

In [ ]:
farom jup.recsys_models.data.short_video_understanding import read_data
from jup.recsys_models.data.short_video_understanding import process_features

In [ ]:
from jup.recsys_models.features import SparseFeature
from jup.recsys_models.features import DenseFeature

In [ ]:
from jup.recsys_models.core.inputs import get_feature_names

In [ ]:
from jup.recsys_models.models.wide_and_deep import WDL

In [ ]:
df = read_data()

In [ ]:
df

In [ ]:
sparse_features = ["uid", "user_city", "item_id", "author_id", "item_city", "channel", "music_id", "device"]
dense_features = ["duration_time"]

processed_df = process_features(df, sparse_features, dense_features)

In [ ]:
processed_df

In [ ]:
# Need to figure out what + 1 here
fixlen_feature_columns = ([
    SparseFeature(feat, vocabulary_size=processed_df[feat].max() + 1, embedding_dim=4) for feat in sparse_features] + 
    [DenseFeature(feat, 1, ) for feat in dense_features])

In [ ]:
dnn_features = ([SparseFeature(feat, vocabulary_size=processed_df[feat].max() + 1, embedding_dim=4) for feat in sparse_features] 
+ [DenseFeature(feat, 1, ) for feat in dense_features])

In [ ]:
# linear features just to use with linear component purposes
linear_features = ([SparseFeature(feat, vocabulary_size=processed_df[feat].max() + 1, embedding_dim=4) for feat in sparse_features] 
+ [DenseFeature(feat, 1, ) for feat in dense_features])

In [ ]:
fixlen_feature_columns

In [ ]:
dnn_feature_columns = fixlen_feature_columns

In [ ]:
dnn_feature_columns

In [ ]:
feature_names = get_feature_names(dnn_feature_columns)

In [ ]:
feature_names

In [ ]:
df.shape

In [ ]:
split_boundary = int(df.shape[0] * 0.8)

In [ ]:
train, test = df[:split_boundary], df[split_boundary:]
# not the train and test contain both values and labels
# thus we need to run the following command to extract only train inputs

train_model_input = {name: train[name] for name in feature_names}
test_model_input = {name: test[name] for name in feature_names}

In [ ]:
type(train[['finish', 'like']].values)

In [ ]:
type(train_model_input['uid'])

In [ ]:
# Up till now, train model input is dictionary: name -> pandas.core.series.Series

In [ ]:
target = ['finish', 'like']

In [ ]:
model = WDL(
    features=dnn_feature_columns,
    linear_features=linear_features
)

In [ ]:
model.set_optimizer('adagrad')

In [ ]:
model.set_loss_function(loss=["binary_cross_entropy", "binary_cross_entropy"])

In [ ]:
model.set_metrics(metrics=['binary_cross_entropy'])

In [ ]:
model.fit(train_model_input, train[target].values, batch_size=2, epochs=10, verbose=2)

In [ ]:
print(model.feature_col_index)

In [ ]:
print(len(model.tower_dnn_hidden_units))

In [ ]:
model.tower_dnn

In [ ]:
model.outs